services:
  - type: web
    name: business-plan-grader
    runtime: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
